### PR TITLE
Fix edit bug

### LINKED ISSUE #143: Edit command breaks the integrated graph display
The `edit` command seems to break the integrated graph display.

It is likely that the node replacement has some issue. Look into this.

### PR DESCRIPTION
**Pull request by wenmogu**
Closes #143

### CODE REVIEW

**Comment by Xenonym** [comment]
Closes #143

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -109,6 +111,31 @@ public void updatePerson(ReadOnlyPerson target, ReadOnlyPerson editedReadOnlyPer
...
+        for (Relationship oldRelationship: oldRelationships) {
+            //keep a copy of the original relationship
+            Relationship oldRelationshipCopy = new Relationship(oldRelationship);
+
+            Relationship tempNewRelationship = oldRelationship.replacePerson(target, editedPerson);
+
+            ReadOnlyPerson counterPart = oldRelationshipCopy.counterpartOf(target); //the old counterpart
+            //a copy of counterpart to be modified into new counterpart and put into the new relationship
+            ReadOnlyPerson counterPartCopy = new Person(counterPart);
+            Person counterPartCopyCast = (Person) counterPartCopy;
```
Comment (Xenonym) [inline src/main/java/seedu/address/model/AddressBook.java]: Why not just keep `counterPartCopy` as a `Person`?
